# -*- coding: utf-8 -*-
#
# Kapteyn Package documentation build configuration file, created by
# sphinx-quickstart on Wed Jun  3 10:34:58 2009.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

#
# Inject own version of align() into module plot_directive
#
from docutils.parsers.rst import directives
from docutils.parsers.rst.directives.images import Image
from matplotlib.sphinxext import plot_directive
def my_align(arg):
   return directives.choice(arg,Image.align_values)
plot_directive.align = my_align

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.append(os.path.abspath('.'))
sys.path.append(os.path.abspath('../PACKAGE/kapteyn'))
sys.path.append(os.path.abspath('.'))

from kapteyn import __version__ as kapteynversion
print 'Kapteyn Package version', kapteynversion

def setup(app):
   app.add_config_value('draftversion', True, True)

draftversion = True

# -- General configuration -----------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.pngmath', 'sphinx.ext.ifconfig',
              'matplotlib.sphinxext.plot_directive', 'only_directives']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8'

# The master toctree document.
master_doc = 'contents'

# General information about the project.
project = u'Kapteyn Package'
copyright = u'2010-2011, Kapteyn Astronomical Institute'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = kapteynversion
# The full version, including alpha/beta/rc tags.
release = kapteynversion

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of documents that shouldn't be included in the build.
#unused_docs = []
unused_docs = ['ascarray']

# List of directories, relative to source directory, that shouldn't be searched
# for source files.
exclude_trees = ['_build']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  Major themes that come with
# Sphinx are currently 'default' and 'sphinxdoc'.
#html_theme = 'default'
html_theme = 'kapteyn-theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
   'stickysidebar':   True,
   'rightsidebar':    True,
   'relbarbgcolor':  'brown',
   'sidebarbgcolor': 'darkgreen',
   'headtextcolor':  'black',
###   'linkcolor':      '#34812A'
}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []
html_theme_path = ['.']

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
html_short_title = 'Kapteyn Package'

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
###html_logo = 'KapteynLogo-s.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = 'Kapteyn.ico'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'
html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}
html_sidebars = {'index': 'indexsidebar.html'}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}
html_additional_pages = {'index': 'index.html'}

# If false, no module index is generated.
#html_use_modindex = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# If nonempty, this is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = ''

# Output file base name for HTML help builder.
htmlhelp_basename = 'kapteyn'


# -- Options for LaTeX output --------------------------------------------------

latex_elements = {
   'papersize' :    'a4paper',
   'pointsize' :    '10pt',
   'fncychap'  :    '\\usepackage[Glenn]{fncychap}'  # fancy chapter headers
#   'fncychap'  :    ''                               # LaTeX default headers
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
  ('contents', 'kapteyn.tex', u'Kapteyn Package Documentation',
   u'Hans Terlouw\\\\ Martin Vogelaar', 'manual', False),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = 'KapteynLogo.jpg'

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False
latex_use_parts = True

# Additional stuff for the LaTeX preamble.
#latex_preamble = ''

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True
latex_domain_indices = False

latex_show_pagerefs = False

latex_show_urls = False

#
# Transparent formulas. Note: different from Sphinx documentation
# stating '-bg Transparent' which did not work. May be due to the
# subprocess.Popen class. -D reduced because of smaller font used.
#
pngmath_dvipng_args = ['-gamma 1.5', '-D 95', '-bg', 'Transparent']

# ----------------------------------------------------------------------------
# Plot directive configuration
# ----------------------------------------------------------------------------
plot_formats = [('png', 80), ('hires.png', 200), ('pdf', 50)]
