/* Generated by Cython 0.11.2 on Wed Nov 18 13:48:43 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef Py_PYTHON_H
    #error Python headers needed to compile C extensions, please install development version of Python.
#endif
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
  #define PyDict_CheckExact(op) (Py_TYPE(op) == &PyDict_Type)
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PY_FORMAT_SIZE_T ""
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   (((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,
  #define PyType_Modified(t)

  typedef struct {
       void *buf;
       PyObject *obj;
       Py_ssize_t len;
       Py_ssize_t itemsize;
       int readonly;
       int ndim;
       char *format;
       Py_ssize_t *shape;
       Py_ssize_t *strides;
       Py_ssize_t *suboffsets;
       void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)

#endif
#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif
#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif
#if (PY_VERSION_HEX < 0x02060000) || (PY_MAJOR_VERSION >= 3)
  #define Py_TPFLAGS_HAVE_NEWBUFFER 0
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyString_Type                PyBytes_Type
  #define PyString_CheckExact          PyBytes_CheckExact
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
#else
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_Divide(x,y)
  #define PyBytes_Type                 PyString_Type
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) PyInstanceMethod_New(func)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
  #ifndef __fastcall
    #define __fastcall
  #endif
#else
  #define _USE_MATH_DEFINES
#endif
#if PY_VERSION_HEX < 0x02050000
  #define __Pyx_GetAttrString(o,n)   PyObject_GetAttrString((o),((char *)(n)))
  #define __Pyx_SetAttrString(o,n,a) PyObject_SetAttrString((o),((char *)(n)),(a))
  #define __Pyx_DelAttrString(o,n)   PyObject_DelAttrString((o),((char *)(n)))
#else
  #define __Pyx_GetAttrString(o,n)   PyObject_GetAttrString((o),(n))
  #define __Pyx_SetAttrString(o,n,a) PyObject_SetAttrString((o),(n),(a))
  #define __Pyx_DelAttrString(o,n)   PyObject_DelAttrString((o),(n))
#endif
#if PY_VERSION_HEX < 0x02050000
  #define __Pyx_NAMESTR(n) ((char *)(n))
  #define __Pyx_DOCSTR(n)  ((char *)(n))
#else
  #define __Pyx_NAMESTR(n) (n)
  #define __Pyx_DOCSTR(n)  (n)
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#define __PYX_HAVE_API__ascarray
#include "numpy/arrayobject.h"
#include "stdlib.h"
#include "stdio.h"
#include "string.h"
#define __PYX_USE_C99_COMPLEX defined(_Complex_I)


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s; long n; char is_unicode; char intern; char is_identifier;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#if PY_MAJOR_VERSION < 3
#define __Pyx_PyBytes_FromString          PyString_FromString
#define __Pyx_PyBytes_FromStringAndSize   PyString_FromStringAndSize
#define __Pyx_PyBytes_AsString            PyString_AsString
#else
#define __Pyx_PyBytes_FromString          PyBytes_FromString
#define __Pyx_PyBytes_FromStringAndSize   PyBytes_FromStringAndSize
#define __Pyx_PyBytes_AsString            PyBytes_AsString
#endif

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject*);
static INLINE PyObject* __Pyx_PyNumber_Int(PyObject* x);

#if !defined(T_PYSSIZET)
#if PY_VERSION_HEX < 0x02050000
#define T_PYSSIZET T_INT
#elif !defined(T_LONGLONG)
#define T_PYSSIZET \
        ((sizeof(Py_ssize_t) == sizeof(int))  ? T_INT  : \
        ((sizeof(Py_ssize_t) == sizeof(long)) ? T_LONG : -1))
#else
#define T_PYSSIZET \
        ((sizeof(Py_ssize_t) == sizeof(int))          ? T_INT      : \
        ((sizeof(Py_ssize_t) == sizeof(long))         ? T_LONG     : \
        ((sizeof(Py_ssize_t) == sizeof(PY_LONG_LONG)) ? T_LONGLONG : -1)))
#endif
#endif

#if !defined(T_SIZET)
#if !defined(T_ULONGLONG)
#define T_SIZET \
        ((sizeof(size_t) == sizeof(unsigned int))  ? T_UINT  : \
        ((sizeof(size_t) == sizeof(unsigned long)) ? T_ULONG : -1))
#else
#define T_SIZET \
        ((sizeof(size_t) == sizeof(unsigned int))          ? T_UINT      : \
        ((sizeof(size_t) == sizeof(unsigned long))         ? T_ULONG     : \
        ((sizeof(size_t) == sizeof(unsigned PY_LONG_LONG)) ? T_ULONGLONG : -1)))
#endif
#endif

static INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject*);
static INLINE PyObject * __Pyx_PyInt_FromSize_t(size_t);
static INLINE size_t __Pyx_PyInt_AsSize_t(PyObject*);

#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))


#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;
static const char **__pyx_f;

static char __pyx_mdoc[] = "\n================\nModule ascarray\n================\n\nThis module is the base containing the function on which :mod:`tabarray`\nhas been built.\n\nFunction ascarray\n-----------------\n\n.. autofunction:: ascarray(filename[, comchar='#!', sepchar=', \\\\t', lines=None, bad=None])\n\n";


#ifdef CYTHON_REFNANNY
typedef struct {
  void (*INCREF)(void*, PyObject*, int);
  void (*DECREF)(void*, PyObject*, int);
  void (*GOTREF)(void*, PyObject*, int);
  void (*GIVEREF)(void*, PyObject*, int);
  void* (*NewContext)(const char*, int, const char*);
  void (*FinishContext)(void**);
} __Pyx_RefnannyAPIStruct;
static __Pyx_RefnannyAPIStruct *__Pyx_Refnanny = NULL;
#define __Pyx_ImportRefcountAPI(name)   (__Pyx_RefnannyAPIStruct *) PyCObject_Import((char *)name, (char *)"RefnannyAPI")
#define __Pyx_INCREF(r) __Pyx_Refnanny->INCREF(__pyx_refchk, (PyObject *)(r), __LINE__)
#define __Pyx_DECREF(r) __Pyx_Refnanny->DECREF(__pyx_refchk, (PyObject *)(r), __LINE__)
#define __Pyx_GOTREF(r) __Pyx_Refnanny->GOTREF(__pyx_refchk, (PyObject *)(r), __LINE__)
#define __Pyx_GIVEREF(r) __Pyx_Refnanny->GIVEREF(__pyx_refchk, (PyObject *)(r), __LINE__)
#define __Pyx_XDECREF(r) if((r) == NULL) ; else __Pyx_DECREF(r)
#define __Pyx_SetupRefcountContext(name)   void* __pyx_refchk = __Pyx_Refnanny->NewContext((name), __LINE__, __FILE__)
#define __Pyx_FinishRefcountContext()   __Pyx_Refnanny->FinishContext(&__pyx_refchk)
#else
#define __Pyx_INCREF(r) Py_INCREF(r)
#define __Pyx_DECREF(r) Py_DECREF(r)
#define __Pyx_GOTREF(r)
#define __Pyx_GIVEREF(r)
#define __Pyx_XDECREF(r) Py_XDECREF(r)
#define __Pyx_SetupRefcountContext(name)
#define __Pyx_FinishRefcountContext()
#endif /* CYTHON_REFNANNY */
#define __Pyx_XGIVEREF(r) if((r) == NULL) ; else __Pyx_GIVEREF(r)
#define __Pyx_XGOTREF(r) if((r) == NULL) ; else __Pyx_GOTREF(r)

static void __Pyx_RaiseDoubleKeywordsError(
    const char* func_name, PyObject* kw_name); /*proto*/

static void __Pyx_RaiseArgtupleInvalid(const char* func_name, int exact,
    Py_ssize_t num_min, Py_ssize_t num_max, Py_ssize_t num_found); /*proto*/

static int __Pyx_ParseOptionalKeywords(PyObject *kwds, PyObject **argnames[],     PyObject *kwds2, PyObject *values[], Py_ssize_t num_pos_args,     const char* function_name); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static INLINE void __Pyx_ErrRestore(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static INLINE void __Pyx_ErrFetch(PyObject **type, PyObject **value, PyObject **tb); /*proto*/

static INLINE void __Pyx_RaiseNeedMoreValuesError(Py_ssize_t index);

static INLINE void __Pyx_RaiseTooManyValuesError(void);

static PyObject *__Pyx_UnpackItem(PyObject *, Py_ssize_t index); /*proto*/
static int __Pyx_EndUnpack(PyObject *); /*proto*/

static INLINE int __Pyx_StrEq(const char *, const char *); /*proto*/

static INLINE unsigned char __Pyx_PyInt_AsUnsignedChar(PyObject *);

static INLINE unsigned short __Pyx_PyInt_AsUnsignedShort(PyObject *);

static INLINE unsigned int __Pyx_PyInt_AsUnsignedInt(PyObject *);

static INLINE char __Pyx_PyInt_AsChar(PyObject *);

static INLINE short __Pyx_PyInt_AsShort(PyObject *);

static INLINE int __Pyx_PyInt_AsInt(PyObject *);

static INLINE signed char __Pyx_PyInt_AsSignedChar(PyObject *);

static INLINE signed short __Pyx_PyInt_AsSignedShort(PyObject *);

static INLINE signed int __Pyx_PyInt_AsSignedInt(PyObject *);

static INLINE unsigned long __Pyx_PyInt_AsUnsignedLong(PyObject *);

static INLINE unsigned PY_LONG_LONG __Pyx_PyInt_AsUnsignedLongLong(PyObject *);

static INLINE long __Pyx_PyInt_AsLong(PyObject *);

static INLINE PY_LONG_LONG __Pyx_PyInt_AsLongLong(PyObject *);

static INLINE signed long __Pyx_PyInt_AsSignedLong(PyObject *);

static INLINE signed PY_LONG_LONG __Pyx_PyInt_AsSignedLongLong(PyObject *);

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

/* Type declarations */

typedef void __pyx_t_8ascarray_FILE;
/* Module declarations from ascarray */

#define __Pyx_MODULE_NAME "ascarray"
int __pyx_module_is_main_ascarray = 0;

/* Implementation of ascarray */
static char __pyx_k_1[] = "#!";
static char __pyx_k_2[] = ", \t";
static char __pyx_k_3[] = "1.2";
static char __pyx_k___main__[] = "__main__";
static PyObject *__pyx_kp___main__;
static char __pyx_k_filename[] = "filename";
static PyObject *__pyx_kp_filename;
static char __pyx_k_comchar[] = "comchar";
static PyObject *__pyx_kp_comchar;
static char __pyx_k_sepchar[] = "sepchar";
static PyObject *__pyx_kp_sepchar;
static char __pyx_k_lines[] = "lines";
static PyObject *__pyx_kp_lines;
static char __pyx_k_bad[] = "bad";
static PyObject *__pyx_kp_bad;
static char __pyx_k_numpy[] = "numpy";
static PyObject *__pyx_kp_numpy;
static char __pyx_k___version__[] = "__version__";
static PyObject *__pyx_kp___version__;
static char __pyx_k_IOError[] = "IOError";
static PyObject *__pyx_kp_IOError;
static char __pyx_k_IndexError[] = "IndexError";
static PyObject *__pyx_kp_IndexError;
static char __pyx_k_ValueError[] = "ValueError";
static PyObject *__pyx_kp_ValueError;
static char __pyx_k_shape[] = "shape";
static PyObject *__pyx_kp_shape;
static PyObject *__pyx_kp_2;
static PyObject *__pyx_kp_3;
static PyObject *__pyx_builtin_IOError;
static PyObject *__pyx_builtin_IndexError;
static PyObject *__pyx_builtin_ValueError;
static PyObject *__pyx_kp_5;
static PyObject *__pyx_kp_6;
static PyObject *__pyx_kp_7;
static PyObject *__pyx_kp_8;
static PyObject *__pyx_kp_9;
static char __pyx_k_4[] = "r";
static char __pyx_k_5[] = "cannot open %s";
static char __pyx_k_6[] = "\n";
static char __pyx_k_7[] = "%s, line %d: row width error";
static char __pyx_k_8[] = "%s, line %d, column %d: invalid number \"%s\"";
static char __pyx_k_9[] = "%s: no lines of data read";

/* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":62
 * #  Read an ASCII table file and return its data as a NumPy array.
 * #
 * def ascarray(filename, char *comchar='#!', sepchar=', \t', lines=None, bad=None):             # <<<<<<<<<<<<<<
 *    """
 * Read an ASCII table file and return its data as a NumPy array.
 */

static PyObject *__pyx_pf_8ascarray_ascarray(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_8ascarray_ascarray[] = "\nRead an ASCII table file and return its data as a NumPy array.\n\n:param source:\n   a string with the name of a text file containing the table.\n:param comchar:\n   string with characters which are used to designate\n   comments in the input file.  The occurrence of any of these\n   characters on a line causes the rest of the line to be ignored.\n   Empty lines and lines containing only a comment are also ignored.\n   Default: '#!'.\n:param sepchar:\n   a string containing the column separation characters to be used.\n   Columns are separated by any combination of these characters.\n   Default: ', \\\\t'.\n:param lines:\n   a two-element tuple or list specifying a range of lines to be\n   read.  Line numbers are counted from one and the range is\n   inclusive.  So (1,10) specifies the first 10 lines of a file. \n   Comment lines are included in the count.  If any element of\n   the tuple or list is zero, this limit is ignored. So (1,0)\n   specifies the whole file, just like the default None. \n   Default: all lines.\n:param bad:\n   a number to be substituted for any field which cannot be\n   decoded as a number. The default None causes a :exc:`ValueError`\n   exception to be raised in such cases.\n:returns:\n   a NumPy array containing the selected data from the table file.\n:raises:\n   :exc:`IOError`, when the file cannot be opened.\n\n   :exc:`IndexError`, when a line with an inconsistent number of fields is\n   encountered in the input file.\n\n   :exc:`ValueError`: when a field cannot be decoded as a number and\n   no alternative value was specified.\n\n";
static PyObject *__pyx_pf_8ascarray_ascarray(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_filename = 0;
  char *__pyx_v_comchar;
  PyObject *__pyx_v_sepchar = 0;
  PyObject *__pyx_v_lines = 0;
  PyObject *__pyx_v_bad = 0;
  __pyx_t_8ascarray_FILE *__pyx_v_f;
  char __pyx_v_line[32768];
  char *__pyx_v_tokens[10000];
  char *__pyx_v_curline;
  char *__pyx_v_token;
  char *__pyx_v_comstart;
  char *__pyx_v_csep;
  char *__pyx_v_endptr;
  int __pyx_v_i;
  int __pyx_v_column;
  int __pyx_v_ncols;
  int __pyx_v_lineno;
  int __pyx_v_lstart;
  int __pyx_v_lend;
  npy_intp __pyx_v_nvalues;
  int __pyx_v_filesize;
  int __pyx_v_maxitems;
  int __pyx_v_badflag;
  double *__pyx_v_data;
  double __pyx_v_badvalue;
  PyObject *__pyx_v_result;
  PyObject *__pyx_r = NULL;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  char *__pyx_t_1;
  int __pyx_t_2;
  PyObject *__pyx_t_3 = NULL;
  int __pyx_t_4;
  double __pyx_t_5;
  int __pyx_t_6;
  PyObject *__pyx_t_7 = NULL;
  PyObject *__pyx_t_8 = NULL;
  PyObject *__pyx_t_9 = NULL;
  static PyObject **__pyx_pyargnames[] = {&__pyx_kp_filename,&__pyx_kp_comchar,&__pyx_kp_sepchar,&__pyx_kp_lines,&__pyx_kp_bad,0};
  __Pyx_SetupRefcountContext("ascarray");
  __pyx_self = __pyx_self;
  if (unlikely(__pyx_kwds)) {
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    PyObject* values[5] = {0,0,0,0,0};
    values[2] = __pyx_kp_2;
    values[3] = Py_None;
    values[4] = Py_None;
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  5: values[4] = PyTuple_GET_ITEM(__pyx_args, 4);
      case  4: values[3] = PyTuple_GET_ITEM(__pyx_args, 3);
      case  3: values[2] = PyTuple_GET_ITEM(__pyx_args, 2);
      case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_kp_filename);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
      case  1:
      if (kw_args > 0) {
        PyObject* value = PyDict_GetItem(__pyx_kwds, __pyx_kp_comchar);
        if (unlikely(value)) { values[1] = value; kw_args--; }
      }
      case  2:
      if (kw_args > 0) {
        PyObject* value = PyDict_GetItem(__pyx_kwds, __pyx_kp_sepchar);
        if (unlikely(value)) { values[2] = value; kw_args--; }
      }
      case  3:
      if (kw_args > 0) {
        PyObject* value = PyDict_GetItem(__pyx_kwds, __pyx_kp_lines);
        if (unlikely(value)) { values[3] = value; kw_args--; }
      }
      case  4:
      if (kw_args > 0) {
        PyObject* value = PyDict_GetItem(__pyx_kwds, __pyx_kp_bad);
        if (unlikely(value)) { values[4] = value; kw_args--; }
      }
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "ascarray") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_filename = values[0];
    if (values[1]) {
      __pyx_v_comchar = __Pyx_PyBytes_AsString(values[1]); if (unlikely((!__pyx_v_comchar) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    } else {
      __pyx_v_comchar = __pyx_k_1;
    }
    __pyx_v_sepchar = values[2];
    __pyx_v_lines = values[3];
    __pyx_v_bad = values[4];
  } else {
    __pyx_v_comchar = __pyx_k_1;
    __pyx_v_sepchar = __pyx_kp_2;
    __pyx_v_lines = Py_None;
    __pyx_v_bad = Py_None;
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  5: __pyx_v_bad = PyTuple_GET_ITEM(__pyx_args, 4);
      case  4: __pyx_v_lines = PyTuple_GET_ITEM(__pyx_args, 3);
      case  3: __pyx_v_sepchar = PyTuple_GET_ITEM(__pyx_args, 2);
      case  2: __pyx_v_comchar = __Pyx_PyBytes_AsString(PyTuple_GET_ITEM(__pyx_args, 1)); if (unlikely((!__pyx_v_comchar) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      case  1: __pyx_v_filename = PyTuple_GET_ITEM(__pyx_args, 0);
      break;
      default: goto __pyx_L5_argtuple_error;
    }
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("ascarray", 0, 1, 5, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("ascarray.ascarray");
  return NULL;
  __pyx_L4_argument_unpacking_done:;
  __Pyx_INCREF(__pyx_v_sepchar);
  __pyx_v_result = Py_None; __Pyx_INCREF(Py_None);

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":107
 *    cdef char *curline, *token, *comstart, *csep
 *    cdef char *endptr
 *    cdef int i, column, ncols=0, lineno=0, lstart=0, lend=0             # <<<<<<<<<<<<<<
 *    cdef npy_intp nvalues=0
 *    cdef int filesize, maxitems, badflag
 */
  __pyx_v_ncols = 0;
  __pyx_v_lineno = 0;
  __pyx_v_lstart = 0;
  __pyx_v_lend = 0;

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":108
 *    cdef char *endptr
 *    cdef int i, column, ncols=0, lineno=0, lstart=0, lend=0
 *    cdef npy_intp nvalues=0             # <<<<<<<<<<<<<<
 *    cdef int filesize, maxitems, badflag
 *    cdef double *data=NULL, badvalue
 */
  __pyx_v_nvalues = 0;

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":110
 *    cdef npy_intp nvalues=0
 *    cdef int filesize, maxitems, badflag
 *    cdef double *data=NULL, badvalue             # <<<<<<<<<<<<<<
 *    f = fopen(filename, "r")
 *    if f==NULL:
 */
  __pyx_v_data = NULL;

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":111
 *    cdef int filesize, maxitems, badflag
 *    cdef double *data=NULL, badvalue
 *    f = fopen(filename, "r")             # <<<<<<<<<<<<<<
 *    if f==NULL:
 *       raise IOError, 'cannot open %s' % filename
 */
  __pyx_t_1 = __Pyx_PyBytes_AsString(__pyx_v_filename); if (unlikely((!__pyx_t_1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_v_f = fopen(__pyx_t_1, __pyx_k_4);

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":112
 *    cdef double *data=NULL, badvalue
 *    f = fopen(filename, "r")
 *    if f==NULL:             # <<<<<<<<<<<<<<
 *       raise IOError, 'cannot open %s' % filename
 *    fseek(f, 0, SEEK_END)
 */
  __pyx_t_2 = (__pyx_v_f == NULL);
  if (__pyx_t_2) {

    /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":113
 *    f = fopen(filename, "r")
 *    if f==NULL:
 *       raise IOError, 'cannot open %s' % filename             # <<<<<<<<<<<<<<
 *    fseek(f, 0, SEEK_END)
 *    filesize = ftell(f)
 */
    __pyx_t_3 = PyNumber_Remainder(__pyx_kp_5, __pyx_v_filename); if (unlikely(!__pyx_t_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __Pyx_GOTREF(__pyx_t_3);
    __Pyx_Raise(__pyx_builtin_IOError, __pyx_t_3, 0);
    __Pyx_DECREF(__pyx_t_3); __pyx_t_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    goto __pyx_L6;
  }
  __pyx_L6:;

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":114
 *    if f==NULL:
 *       raise IOError, 'cannot open %s' % filename
 *    fseek(f, 0, SEEK_END)             # <<<<<<<<<<<<<<
 *    filesize = ftell(f)
 *    fseek(f, 0, SEEK_SET)
 */
  fseek(__pyx_v_f, 0, SEEK_END);

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":115
 *       raise IOError, 'cannot open %s' % filename
 *    fseek(f, 0, SEEK_END)
 *    filesize = ftell(f)             # <<<<<<<<<<<<<<
 *    fseek(f, 0, SEEK_SET)
 *    sepchar += '\n'
 */
  __pyx_v_filesize = ftell(__pyx_v_f);

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":116
 *    fseek(f, 0, SEEK_END)
 *    filesize = ftell(f)
 *    fseek(f, 0, SEEK_SET)             # <<<<<<<<<<<<<<
 *    sepchar += '\n'
 *    csep = sepchar
 */
  fseek(__pyx_v_f, 0, SEEK_SET);

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":117
 *    filesize = ftell(f)
 *    fseek(f, 0, SEEK_SET)
 *    sepchar += '\n'             # <<<<<<<<<<<<<<
 *    csep = sepchar
 *    badflag = bad is not None
 */
  __pyx_1 = PyNumber_InPlaceAdd(__pyx_v_sepchar, __pyx_kp_6); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_1);
  __Pyx_DECREF(__pyx_v_sepchar);
  __pyx_v_sepchar = __pyx_1;
  __pyx_1 = 0;

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":118
 *    fseek(f, 0, SEEK_SET)
 *    sepchar += '\n'
 *    csep = sepchar             # <<<<<<<<<<<<<<
 *    badflag = bad is not None
 *    if badflag:
 */
  __pyx_t_1 = __Pyx_PyBytes_AsString(__pyx_v_sepchar); if (unlikely((!__pyx_t_1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_v_csep = __pyx_t_1;

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":119
 *    sepchar += '\n'
 *    csep = sepchar
 *    badflag = bad is not None             # <<<<<<<<<<<<<<
 *    if badflag:
 *       badvalue = bad
 */
  __pyx_t_2 = (__pyx_v_bad != Py_None);
  __pyx_v_badflag = __pyx_t_2;

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":120
 *    csep = sepchar
 *    badflag = bad is not None
 *    if badflag:             # <<<<<<<<<<<<<<
 *       badvalue = bad
 *    if lines:
 */
  __pyx_t_4 = __pyx_v_badflag;
  if (__pyx_t_4) {

    /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":121
 *    badflag = bad is not None
 *    if badflag:
 *       badvalue = bad             # <<<<<<<<<<<<<<
 *    if lines:
 *       lstart, lend = lines
 */
    __pyx_t_5 = __pyx_PyFloat_AsDouble(__pyx_v_bad); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_v_badvalue = __pyx_t_5;
    goto __pyx_L7;
  }
  __pyx_L7:;

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":122
 *    if badflag:
 *       badvalue = bad
 *    if lines:             # <<<<<<<<<<<<<<
 *       lstart, lend = lines
 *    while fgets(line, 32768, f) != NULL:
 */
  __pyx_t_2 = __Pyx_PyObject_IsTrue(__pyx_v_lines); if (unlikely(__pyx_t_2 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__pyx_t_2) {

    /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":123
 *       badvalue = bad
 *    if lines:
 *       lstart, lend = lines             # <<<<<<<<<<<<<<
 *    while fgets(line, 32768, f) != NULL:
 *       lineno += 1
 */
    if (PyTuple_CheckExact(__pyx_v_lines) && likely(PyTuple_GET_SIZE(__pyx_v_lines) == 2)) {
      PyObject* tuple = __pyx_v_lines;
      __pyx_2 = PyTuple_GET_ITEM(tuple, 0); __Pyx_INCREF(__pyx_2);
      __pyx_t_4 = __Pyx_PyInt_AsInt(__pyx_2); if (unlikely((__pyx_t_4 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __Pyx_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_2 = PyTuple_GET_ITEM(tuple, 1); __Pyx_INCREF(__pyx_2);
      __pyx_t_6 = __Pyx_PyInt_AsInt(__pyx_2); if (unlikely((__pyx_t_6 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __Pyx_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_v_lstart = __pyx_t_4;
      __pyx_v_lend = __pyx_t_6;
    } else {
      __pyx_1 = PyObject_GetIter(__pyx_v_lines); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __Pyx_GOTREF(__pyx_1);
      __pyx_2 = __Pyx_UnpackItem(__pyx_1, 0); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __Pyx_GOTREF(__pyx_2);
      __pyx_t_6 = __Pyx_PyInt_AsInt(__pyx_2); if (unlikely((__pyx_t_6 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __Pyx_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_2 = __Pyx_UnpackItem(__pyx_1, 1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __Pyx_GOTREF(__pyx_2);
      __pyx_t_4 = __Pyx_PyInt_AsInt(__pyx_2); if (unlikely((__pyx_t_4 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __Pyx_DECREF(__pyx_2); __pyx_2 = 0;
      if (__Pyx_EndUnpack(__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __Pyx_DECREF(__pyx_1); __pyx_1 = 0;
      __pyx_v_lstart = __pyx_t_6;
      __pyx_v_lend = __pyx_t_4;
    }
    goto __pyx_L8;
  }
  __pyx_L8:;

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":124
 *    if lines:
 *       lstart, lend = lines
 *    while fgets(line, 32768, f) != NULL:             # <<<<<<<<<<<<<<
 *       lineno += 1
 *       if lstart>0 and lineno<lstart:
 */
  while (1) {
    __pyx_t_2 = (fgets(__pyx_v_line, 32768, __pyx_v_f) != NULL);
    if (!__pyx_t_2) break;

    /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":125
 *       lstart, lend = lines
 *    while fgets(line, 32768, f) != NULL:
 *       lineno += 1             # <<<<<<<<<<<<<<
 *       if lstart>0 and lineno<lstart:
 *          continue
 */
    __pyx_v_lineno += 1;

    /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":126
 *    while fgets(line, 32768, f) != NULL:
 *       lineno += 1
 *       if lstart>0 and lineno<lstart:             # <<<<<<<<<<<<<<
 *          continue
 *       if lend>0 and lineno>lend:
 */
    if ((__pyx_v_lstart > 0)) {
      __pyx_t_2 = (__pyx_v_lineno < __pyx_v_lstart);
    } else {
      __pyx_t_2 = (__pyx_v_lstart > 0);
    }
    if (__pyx_t_2) {

      /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":127
 *       lineno += 1
 *       if lstart>0 and lineno<lstart:
 *          continue             # <<<<<<<<<<<<<<
 *       if lend>0 and lineno>lend:
 *          break
 */
      goto __pyx_L9_continue;
      goto __pyx_L11;
    }
    __pyx_L11:;

    /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":128
 *       if lstart>0 and lineno<lstart:
 *          continue
 *       if lend>0 and lineno>lend:             # <<<<<<<<<<<<<<
 *          break
 *       comstart = strpbrk(line, comchar)
 */
    if ((__pyx_v_lend > 0)) {
      __pyx_t_2 = (__pyx_v_lineno > __pyx_v_lend);
    } else {
      __pyx_t_2 = (__pyx_v_lend > 0);
    }
    if (__pyx_t_2) {

      /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":129
 *          continue
 *       if lend>0 and lineno>lend:
 *          break             # <<<<<<<<<<<<<<
 *       comstart = strpbrk(line, comchar)
 *       if comstart!=NULL:
 */
      goto __pyx_L10_break;
      goto __pyx_L12;
    }
    __pyx_L12:;

    /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":130
 *       if lend>0 and lineno>lend:
 *          break
 *       comstart = strpbrk(line, comchar)             # <<<<<<<<<<<<<<
 *       if comstart!=NULL:
 *          comstart[0] = 0
 */
    __pyx_v_comstart = strpbrk(__pyx_v_line, __pyx_v_comchar);

    /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":131
 *          break
 *       comstart = strpbrk(line, comchar)
 *       if comstart!=NULL:             # <<<<<<<<<<<<<<
 *          comstart[0] = 0
 *       column = 0
 */
    __pyx_t_2 = (__pyx_v_comstart != NULL);
    if (__pyx_t_2) {

      /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":132
 *       comstart = strpbrk(line, comchar)
 *       if comstart!=NULL:
 *          comstart[0] = 0             # <<<<<<<<<<<<<<
 *       column = 0
 *       curline = line
 */
      (__pyx_v_comstart[0]) = 0;
      goto __pyx_L13;
    }
    __pyx_L13:;

    /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":133
 *       if comstart!=NULL:
 *          comstart[0] = 0
 *       column = 0             # <<<<<<<<<<<<<<
 *       curline = line
 *       while 1:
 */
    __pyx_v_column = 0;

    /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":134
 *          comstart[0] = 0
 *       column = 0
 *       curline = line             # <<<<<<<<<<<<<<
 *       while 1:
 *          token = strtok(curline, csep)
 */
    __pyx_v_curline = __pyx_v_line;

    /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":135
 *       column = 0
 *       curline = line
 *       while 1:             # <<<<<<<<<<<<<<
 *          token = strtok(curline, csep)
 *          curline = NULL
 */
    while (1) {
      __pyx_t_2 = 1;
      if (!__pyx_t_2) break;

      /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":136
 *       curline = line
 *       while 1:
 *          token = strtok(curline, csep)             # <<<<<<<<<<<<<<
 *          curline = NULL
 *          if token != NULL:
 */
      __pyx_v_token = strtok(__pyx_v_curline, __pyx_v_csep);

      /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":137
 *       while 1:
 *          token = strtok(curline, csep)
 *          curline = NULL             # <<<<<<<<<<<<<<
 *          if token != NULL:
 *             tokens[column] = token
 */
      __pyx_v_curline = NULL;

      /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":138
 *          token = strtok(curline, csep)
 *          curline = NULL
 *          if token != NULL:             # <<<<<<<<<<<<<<
 *             tokens[column] = token
 *             column += 1
 */
      __pyx_t_2 = (__pyx_v_token != NULL);
      if (__pyx_t_2) {

        /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":139
 *          curline = NULL
 *          if token != NULL:
 *             tokens[column] = token             # <<<<<<<<<<<<<<
 *             column += 1
 *          else:
 */
        (__pyx_v_tokens[__pyx_v_column]) = __pyx_v_token;

        /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":140
 *          if token != NULL:
 *             tokens[column] = token
 *             column += 1             # <<<<<<<<<<<<<<
 *          else:
 *             if column>0:
 */
        __pyx_v_column += 1;
        goto __pyx_L16;
      }
      /*else*/ {

        /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":142
 *             column += 1
 *          else:
 *             if column>0:             # <<<<<<<<<<<<<<
 *                if ncols>0:
 *                   if ncols!=column:
 */
        __pyx_t_2 = (__pyx_v_column > 0);
        if (__pyx_t_2) {

          /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":143
 *          else:
 *             if column>0:
 *                if ncols>0:             # <<<<<<<<<<<<<<
 *                   if ncols!=column:
 *                      fclose(f)
 */
          __pyx_t_2 = (__pyx_v_ncols > 0);
          if (__pyx_t_2) {

            /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":144
 *             if column>0:
 *                if ncols>0:
 *                   if ncols!=column:             # <<<<<<<<<<<<<<
 *                      fclose(f)
 *                      raise IndexError, \
 */
            __pyx_t_2 = (__pyx_v_ncols != __pyx_v_column);
            if (__pyx_t_2) {

              /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":145
 *                if ncols>0:
 *                   if ncols!=column:
 *                      fclose(f)             # <<<<<<<<<<<<<<
 *                      raise IndexError, \
 *                         '%s, line %d: row width error' % (filename, lineno)
 */
              fclose(__pyx_v_f);

              /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":147
 *                      fclose(f)
 *                      raise IndexError, \
 *                         '%s, line %d: row width error' % (filename, lineno)             # <<<<<<<<<<<<<<
 *                else:
 *                   ncols = column
 */
              __pyx_t_3 = PyInt_FromLong(__pyx_v_lineno); if (unlikely(!__pyx_t_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
              __Pyx_GOTREF(__pyx_t_3);
              __pyx_t_7 = PyTuple_New(2); if (unlikely(!__pyx_t_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
              __Pyx_GOTREF(((PyObject *)__pyx_t_7));
              __Pyx_INCREF(__pyx_v_filename);
              PyTuple_SET_ITEM(__pyx_t_7, 0, __pyx_v_filename);
              __Pyx_GIVEREF(__pyx_v_filename);
              PyTuple_SET_ITEM(__pyx_t_7, 1, __pyx_t_3);
              __Pyx_GIVEREF(__pyx_t_3);
              __pyx_t_3 = 0;
              __pyx_t_3 = PyNumber_Remainder(__pyx_kp_7, ((PyObject *)__pyx_t_7)); if (unlikely(!__pyx_t_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
              __Pyx_GOTREF(__pyx_t_3);
              __Pyx_DECREF(((PyObject *)__pyx_t_7)); __pyx_t_7 = 0;
              __Pyx_Raise(__pyx_builtin_IndexError, __pyx_t_3, 0);
              __Pyx_DECREF(__pyx_t_3); __pyx_t_3 = 0;
              {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
              goto __pyx_L19;
            }
            __pyx_L19:;
            goto __pyx_L18;
          }
          /*else*/ {

            /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":149
 *                         '%s, line %d: row width error' % (filename, lineno)
 *                else:
 *                   ncols = column             # <<<<<<<<<<<<<<
 *                   maxitems = <int>(1.3*ncols*filesize/strlen(line))+ncols
 *                   data = <double*>malloc(maxitems*sizeof(double))
 */
            __pyx_v_ncols = __pyx_v_column;

            /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":150
 *                else:
 *                   ncols = column
 *                   maxitems = <int>(1.3*ncols*filesize/strlen(line))+ncols             # <<<<<<<<<<<<<<
 *                   data = <double*>malloc(maxitems*sizeof(double))
 *             for i from 0 <= i <column:
 */
            __pyx_v_maxitems = (((int)(((1.3 * __pyx_v_ncols) * __pyx_v_filesize) / strlen(__pyx_v_line))) + __pyx_v_ncols);

            /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":151
 *                   ncols = column
 *                   maxitems = <int>(1.3*ncols*filesize/strlen(line))+ncols
 *                   data = <double*>malloc(maxitems*sizeof(double))             # <<<<<<<<<<<<<<
 *             for i from 0 <= i <column:
 *                if nvalues>=maxitems:
 */
            __pyx_v_data = ((double *)malloc((__pyx_v_maxitems * (sizeof(double)))));
          }
          __pyx_L18:;
          goto __pyx_L17;
        }
        __pyx_L17:;

        /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":152
 *                   maxitems = <int>(1.3*ncols*filesize/strlen(line))+ncols
 *                   data = <double*>malloc(maxitems*sizeof(double))
 *             for i from 0 <= i <column:             # <<<<<<<<<<<<<<
 *                if nvalues>=maxitems:
 *                   maxitems = <int>(1.3*maxitems)+ncols
 */
        __pyx_t_4 = __pyx_v_column;
        for (__pyx_v_i = 0; __pyx_v_i < __pyx_t_4; __pyx_v_i++) {

          /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":153
 *                   data = <double*>malloc(maxitems*sizeof(double))
 *             for i from 0 <= i <column:
 *                if nvalues>=maxitems:             # <<<<<<<<<<<<<<
 *                   maxitems = <int>(1.3*maxitems)+ncols
 *                   data = <double*>realloc(data, maxitems*sizeof(double))
 */
          __pyx_t_2 = (__pyx_v_nvalues >= __pyx_v_maxitems);
          if (__pyx_t_2) {

            /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":154
 *             for i from 0 <= i <column:
 *                if nvalues>=maxitems:
 *                   maxitems = <int>(1.3*maxitems)+ncols             # <<<<<<<<<<<<<<
 *                   data = <double*>realloc(data, maxitems*sizeof(double))
 *                data[nvalues] = strtod(tokens[i], &endptr)
 */
            __pyx_v_maxitems = (((int)(1.3 * __pyx_v_maxitems)) + __pyx_v_ncols);

            /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":155
 *                if nvalues>=maxitems:
 *                   maxitems = <int>(1.3*maxitems)+ncols
 *                   data = <double*>realloc(data, maxitems*sizeof(double))             # <<<<<<<<<<<<<<
 *                data[nvalues] = strtod(tokens[i], &endptr)
 *                if endptr[0]!=0:
 */
            __pyx_v_data = ((double *)realloc(__pyx_v_data, (__pyx_v_maxitems * (sizeof(double)))));
            goto __pyx_L22;
          }
          __pyx_L22:;

          /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":156
 *                   maxitems = <int>(1.3*maxitems)+ncols
 *                   data = <double*>realloc(data, maxitems*sizeof(double))
 *                data[nvalues] = strtod(tokens[i], &endptr)             # <<<<<<<<<<<<<<
 *                if endptr[0]!=0:
 *                   if badflag:
 */
          (__pyx_v_data[__pyx_v_nvalues]) = strtod((__pyx_v_tokens[__pyx_v_i]), (&__pyx_v_endptr));

          /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":157
 *                   data = <double*>realloc(data, maxitems*sizeof(double))
 *                data[nvalues] = strtod(tokens[i], &endptr)
 *                if endptr[0]!=0:             # <<<<<<<<<<<<<<
 *                   if badflag:
 *                      data[nvalues] = badvalue
 */
          __pyx_t_2 = ((__pyx_v_endptr[0]) != 0);
          if (__pyx_t_2) {

            /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":158
 *                data[nvalues] = strtod(tokens[i], &endptr)
 *                if endptr[0]!=0:
 *                   if badflag:             # <<<<<<<<<<<<<<
 *                      data[nvalues] = badvalue
 *                   else:
 */
            __pyx_t_6 = __pyx_v_badflag;
            if (__pyx_t_6) {

              /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":159
 *                if endptr[0]!=0:
 *                   if badflag:
 *                      data[nvalues] = badvalue             # <<<<<<<<<<<<<<
 *                   else:
 *                      fclose(f)
 */
              (__pyx_v_data[__pyx_v_nvalues]) = __pyx_v_badvalue;
              goto __pyx_L24;
            }
            /*else*/ {

              /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":161
 *                      data[nvalues] = badvalue
 *                   else:
 *                      fclose(f)             # <<<<<<<<<<<<<<
 *                      raise ValueError, \
 *                       '%s, line %d, column %d: invalid number "%s"' \
 */
              fclose(__pyx_v_f);

              /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":164
 *                      raise ValueError, \
 *                       '%s, line %d, column %d: invalid number "%s"' \
 *                       % (filename, lineno, i+1, tokens[i])             # <<<<<<<<<<<<<<
 *                nvalues += 1
 *             break
 */
              __pyx_t_3 = PyInt_FromLong(__pyx_v_lineno); if (unlikely(!__pyx_t_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
              __Pyx_GOTREF(__pyx_t_3);
              __pyx_t_7 = PyInt_FromLong((__pyx_v_i + 1)); if (unlikely(!__pyx_t_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
              __Pyx_GOTREF(__pyx_t_7);
              __pyx_t_8 = __Pyx_PyBytes_FromString((__pyx_v_tokens[__pyx_v_i])); if (unlikely(!__pyx_t_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
              __Pyx_GOTREF(__pyx_t_8);
              __pyx_t_9 = PyTuple_New(4); if (unlikely(!__pyx_t_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
              __Pyx_GOTREF(((PyObject *)__pyx_t_9));
              __Pyx_INCREF(__pyx_v_filename);
              PyTuple_SET_ITEM(__pyx_t_9, 0, __pyx_v_filename);
              __Pyx_GIVEREF(__pyx_v_filename);
              PyTuple_SET_ITEM(__pyx_t_9, 1, __pyx_t_3);
              __Pyx_GIVEREF(__pyx_t_3);
              PyTuple_SET_ITEM(__pyx_t_9, 2, __pyx_t_7);
              __Pyx_GIVEREF(__pyx_t_7);
              PyTuple_SET_ITEM(__pyx_t_9, 3, __pyx_t_8);
              __Pyx_GIVEREF(__pyx_t_8);
              __pyx_t_3 = 0;
              __pyx_t_7 = 0;
              __pyx_t_8 = 0;
              __pyx_t_8 = PyNumber_Remainder(__pyx_kp_8, ((PyObject *)__pyx_t_9)); if (unlikely(!__pyx_t_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
              __Pyx_GOTREF(__pyx_t_8);
              __Pyx_DECREF(((PyObject *)__pyx_t_9)); __pyx_t_9 = 0;
              __Pyx_Raise(__pyx_builtin_ValueError, __pyx_t_8, 0);
              __Pyx_DECREF(__pyx_t_8); __pyx_t_8 = 0;
              {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
            }
            __pyx_L24:;
            goto __pyx_L23;
          }
          __pyx_L23:;

          /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":165
 *                       '%s, line %d, column %d: invalid number "%s"' \
 *                       % (filename, lineno, i+1, tokens[i])
 *                nvalues += 1             # <<<<<<<<<<<<<<
 *             break
 *    fclose(f)
 */
          __pyx_v_nvalues += 1;
        }

        /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":166
 *                       % (filename, lineno, i+1, tokens[i])
 *                nvalues += 1
 *             break             # <<<<<<<<<<<<<<
 *    fclose(f)
 *    if not data:
 */
        goto __pyx_L15_break;
      }
      __pyx_L16:;
    }
    __pyx_L15_break:;
    __pyx_L9_continue:;
  }
  __pyx_L10_break:;

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":167
 *                nvalues += 1
 *             break
 *    fclose(f)             # <<<<<<<<<<<<<<
 *    if not data:
 *       raise IndexError, '%s: no lines of data read' % filename
 */
  fclose(__pyx_v_f);

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":168
 *             break
 *    fclose(f)
 *    if not data:             # <<<<<<<<<<<<<<
 *       raise IndexError, '%s: no lines of data read' % filename
 *    data = <double*>realloc(data, nvalues*sizeof(double))
 */
  __pyx_t_2 = (!(__pyx_v_data != 0));
  if (__pyx_t_2) {

    /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":169
 *    fclose(f)
 *    if not data:
 *       raise IndexError, '%s: no lines of data read' % filename             # <<<<<<<<<<<<<<
 *    data = <double*>realloc(data, nvalues*sizeof(double))
 *    result = PyArray_SimpleNewFromData(1, &nvalues, NPY_DOUBLE, data)
 */
    __pyx_t_8 = PyNumber_Remainder(__pyx_kp_9, __pyx_v_filename); if (unlikely(!__pyx_t_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __Pyx_GOTREF(__pyx_t_8);
    __Pyx_Raise(__pyx_builtin_IndexError, __pyx_t_8, 0);
    __Pyx_DECREF(__pyx_t_8); __pyx_t_8 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    goto __pyx_L25;
  }
  __pyx_L25:;

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":170
 *    if not data:
 *       raise IndexError, '%s: no lines of data read' % filename
 *    data = <double*>realloc(data, nvalues*sizeof(double))             # <<<<<<<<<<<<<<
 *    result = PyArray_SimpleNewFromData(1, &nvalues, NPY_DOUBLE, data)
 *    result.shape = (nvalues/ncols, ncols)
 */
  __pyx_v_data = ((double *)realloc(__pyx_v_data, (__pyx_v_nvalues * (sizeof(double)))));

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":171
 *       raise IndexError, '%s: no lines of data read' % filename
 *    data = <double*>realloc(data, nvalues*sizeof(double))
 *    result = PyArray_SimpleNewFromData(1, &nvalues, NPY_DOUBLE, data)             # <<<<<<<<<<<<<<
 *    result.shape = (nvalues/ncols, ncols)
 *    return result
 */
  __pyx_t_8 = PyArray_SimpleNewFromData(1, (&__pyx_v_nvalues), NPY_DOUBLE, __pyx_v_data); if (unlikely(!__pyx_t_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 171; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_8);
  __Pyx_DECREF(__pyx_v_result);
  __pyx_v_result = __pyx_t_8;
  __pyx_t_8 = 0;

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":172
 *    data = <double*>realloc(data, nvalues*sizeof(double))
 *    result = PyArray_SimpleNewFromData(1, &nvalues, NPY_DOUBLE, data)
 *    result.shape = (nvalues/ncols, ncols)             # <<<<<<<<<<<<<<
 *    return result
 * 
 */
  __pyx_t_8 = PyInt_FromLong((__pyx_v_nvalues / __pyx_v_ncols)); if (unlikely(!__pyx_t_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_8);
  __pyx_t_9 = PyInt_FromLong(__pyx_v_ncols); if (unlikely(!__pyx_t_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_9);
  __pyx_t_7 = PyTuple_New(2); if (unlikely(!__pyx_t_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(((PyObject *)__pyx_t_7));
  PyTuple_SET_ITEM(__pyx_t_7, 0, __pyx_t_8);
  __Pyx_GIVEREF(__pyx_t_8);
  PyTuple_SET_ITEM(__pyx_t_7, 1, __pyx_t_9);
  __Pyx_GIVEREF(__pyx_t_9);
  __pyx_t_8 = 0;
  __pyx_t_9 = 0;
  if (PyObject_SetAttr(__pyx_v_result, __pyx_kp_shape, ((PyObject *)__pyx_t_7)) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(((PyObject *)__pyx_t_7)); __pyx_t_7 = 0;

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":173
 *    result = PyArray_SimpleNewFromData(1, &nvalues, NPY_DOUBLE, data)
 *    result.shape = (nvalues/ncols, ncols)
 *    return result             # <<<<<<<<<<<<<<
 * 
 * __version__ = '1.2'
 */
  __Pyx_XDECREF(__pyx_r);
  __Pyx_INCREF(__pyx_v_result);
  __pyx_r = __pyx_v_result;
  goto __pyx_L0;

  __pyx_r = Py_None; __Pyx_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_1);
  __Pyx_XDECREF(__pyx_2);
  __Pyx_XDECREF(__pyx_t_3);
  __Pyx_XDECREF(__pyx_t_7);
  __Pyx_XDECREF(__pyx_t_8);
  __Pyx_XDECREF(__pyx_t_9);
  __Pyx_AddTraceback("ascarray.ascarray");
  __pyx_r = NULL;
  __pyx_L0:;
  __Pyx_DECREF(__pyx_v_result);
  __Pyx_DECREF(__pyx_v_sepchar);
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_FinishRefcountContext();
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {__Pyx_NAMESTR("ascarray"), (PyCFunction)__pyx_pf_8ascarray_ascarray, METH_VARARGS|METH_KEYWORDS, __Pyx_DOCSTR(__pyx_doc_8ascarray_ascarray)},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef __pyx_moduledef = {
    PyModuleDef_HEAD_INIT,
    __Pyx_NAMESTR("ascarray"),
    __Pyx_DOCSTR(__pyx_mdoc), /* m_doc */
    -1, /* m_size */
    __pyx_methods /* m_methods */,
    NULL, /* m_reload */
    NULL, /* m_traverse */
    NULL, /* m_clear */
    NULL /* m_free */
};
#endif

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp___main__, __pyx_k___main__, sizeof(__pyx_k___main__), 1, 1, 1},
  {&__pyx_kp_filename, __pyx_k_filename, sizeof(__pyx_k_filename), 1, 1, 1},
  {&__pyx_kp_comchar, __pyx_k_comchar, sizeof(__pyx_k_comchar), 1, 1, 1},
  {&__pyx_kp_sepchar, __pyx_k_sepchar, sizeof(__pyx_k_sepchar), 1, 1, 1},
  {&__pyx_kp_lines, __pyx_k_lines, sizeof(__pyx_k_lines), 1, 1, 1},
  {&__pyx_kp_bad, __pyx_k_bad, sizeof(__pyx_k_bad), 1, 1, 1},
  {&__pyx_kp_numpy, __pyx_k_numpy, sizeof(__pyx_k_numpy), 1, 1, 1},
  {&__pyx_kp___version__, __pyx_k___version__, sizeof(__pyx_k___version__), 1, 1, 1},
  {&__pyx_kp_IOError, __pyx_k_IOError, sizeof(__pyx_k_IOError), 1, 1, 1},
  {&__pyx_kp_IndexError, __pyx_k_IndexError, sizeof(__pyx_k_IndexError), 1, 1, 1},
  {&__pyx_kp_ValueError, __pyx_k_ValueError, sizeof(__pyx_k_ValueError), 1, 1, 1},
  {&__pyx_kp_shape, __pyx_k_shape, sizeof(__pyx_k_shape), 1, 1, 1},
  {&__pyx_kp_2, __pyx_k_2, sizeof(__pyx_k_2), 0, 0, 0},
  {&__pyx_kp_3, __pyx_k_3, sizeof(__pyx_k_3), 0, 0, 0},
  {&__pyx_kp_5, __pyx_k_5, sizeof(__pyx_k_5), 0, 0, 0},
  {&__pyx_kp_6, __pyx_k_6, sizeof(__pyx_k_6), 0, 0, 0},
  {&__pyx_kp_7, __pyx_k_7, sizeof(__pyx_k_7), 0, 0, 0},
  {&__pyx_kp_8, __pyx_k_8, sizeof(__pyx_k_8), 0, 0, 0},
  {&__pyx_kp_9, __pyx_k_9, sizeof(__pyx_k_9), 0, 0, 0},
  {0, 0, 0, 0, 0, 0}
};
static int __Pyx_InitCachedBuiltins(void) {
  __pyx_builtin_IOError = __Pyx_GetName(__pyx_b, __pyx_kp_IOError); if (!__pyx_builtin_IOError) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_builtin_IndexError = __Pyx_GetName(__pyx_b, __pyx_kp_IndexError); if (!__pyx_builtin_IndexError) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_builtin_ValueError = __Pyx_GetName(__pyx_b, __pyx_kp_ValueError); if (!__pyx_builtin_ValueError) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  return 0;
  __pyx_L1_error:;
  return -1;
}

static int __Pyx_InitGlobals(void) {
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  return 0;
  __pyx_L1_error:;
  return -1;
}

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initascarray(void); /*proto*/
PyMODINIT_FUNC initascarray(void)
#else
PyMODINIT_FUNC PyInit_ascarray(void); /*proto*/
PyMODINIT_FUNC PyInit_ascarray(void)
#endif
{
  PyObject *__pyx_1 = 0;
  #ifdef CYTHON_REFNANNY
  void* __pyx_refchk = NULL;
  __Pyx_Refnanny = __Pyx_ImportRefcountAPI("refnanny");
  if (!__Pyx_Refnanny) {
      PyErr_Clear();
      __Pyx_Refnanny = __Pyx_ImportRefcountAPI("Cython.Runtime.refnanny");
      if (!__Pyx_Refnanny)
          Py_FatalError("failed to import refnanny module");
  }
  __pyx_refchk = __Pyx_Refnanny->NewContext("PyMODINIT_FUNC PyInit_ascarray(void)", __LINE__, __FILE__);
  #endif
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Library function declarations ---*/
  __pyx_init_filenames();
  /*--- Threads initialization code ---*/
  #if defined(__PYX_FORCE_INIT_THREADS) && __PYX_FORCE_INIT_THREADS
  #ifdef WITH_THREAD /* Python build with threading support? */
  PyEval_InitThreads();
  #endif
  #endif
  /*--- Initialize various global constants etc. ---*/
  if (unlikely(__Pyx_InitGlobals() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Module creation code ---*/
  #if PY_MAJOR_VERSION < 3
  __pyx_m = Py_InitModule4(__Pyx_NAMESTR("ascarray"), __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  #else
  __pyx_m = PyModule_Create(&__pyx_moduledef);
  #endif
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  #if PY_MAJOR_VERSION < 3
  Py_INCREF(__pyx_m);
  #endif
  __pyx_b = PyImport_AddModule(__Pyx_NAMESTR(__Pyx_BUILTIN_MODULE_NAME));
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (__Pyx_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (__pyx_module_is_main_ascarray) {
    if (__Pyx_SetAttrString(__pyx_m, "__name__", __pyx_kp___main__) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  }
  /*--- Builtin init code ---*/
  if (unlikely(__Pyx_InitCachedBuiltins() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  /*--- Type import code ---*/
  /*--- Function import code ---*/
  /*--- Execution code ---*/

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":16
 * """
 * 
 * import numpy             # <<<<<<<<<<<<<<
 * 
 * # ==========================================================================
 */
  __pyx_1 = __Pyx_Import(__pyx_kp_numpy, 0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_1);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_numpy, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":55
 *    int strlen(char *s)
 * 
 * import_array()             # <<<<<<<<<<<<<<
 * 
 * # ==========================================================================
 */
  import_array();

  /* "/Users/users/terlouw/KAPTEYN/DISTRIBUTION/src/ascarray.pyx":175
 *    return result
 * 
 * __version__ = '1.2'             # <<<<<<<<<<<<<<
 */
  if (PyObject_SetAttr(__pyx_m, __pyx_kp___version__, __pyx_kp_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 175; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_1);
  __Pyx_AddTraceback("ascarray");
  Py_DECREF(__pyx_m); __pyx_m = 0;
  __pyx_L0:;
  __Pyx_FinishRefcountContext();
  #if PY_MAJOR_VERSION < 3
  return;
  #else
  return __pyx_m;
  #endif
}

static const char *__pyx_filenames[] = {
  "ascarray.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static void __Pyx_RaiseDoubleKeywordsError(
    const char* func_name,
    PyObject* kw_name)
{
    PyErr_Format(PyExc_TypeError,
        #if PY_MAJOR_VERSION >= 3
        "%s() got multiple values for keyword argument '%U'", func_name, kw_name);
        #else
        "%s() got multiple values for keyword argument '%s'", func_name,
        PyString_AS_STRING(kw_name));
        #endif
}

static void __Pyx_RaiseArgtupleInvalid(
    const char* func_name,
    int exact,
    Py_ssize_t num_min,
    Py_ssize_t num_max,
    Py_ssize_t num_found)
{
    Py_ssize_t num_expected;
    const char *number, *more_or_less;

    if (num_found < num_min) {
        num_expected = num_min;
        more_or_less = "at least";
    } else {
        num_expected = num_max;
        more_or_less = "at most";
    }
    if (exact) {
        more_or_less = "exactly";
    }
    number = (num_expected == 1) ? "" : "s";
    PyErr_Format(PyExc_TypeError,
        #if PY_VERSION_HEX < 0x02050000
            "%s() takes %s %d positional argument%s (%d given)",
        #else
            "%s() takes %s %zd positional argument%s (%zd given)",
        #endif
        func_name, more_or_less, num_expected, number, num_found);
}

static int __Pyx_ParseOptionalKeywords(
    PyObject *kwds,
    PyObject **argnames[],
    PyObject *kwds2,
    PyObject *values[],
    Py_ssize_t num_pos_args,
    const char* function_name)
{
    PyObject *key = 0, *value = 0;
    Py_ssize_t pos = 0;
    PyObject*** name;
    PyObject*** first_kw_arg = argnames + num_pos_args;

    while (PyDict_Next(kwds, &pos, &key, &value)) {
        name = first_kw_arg;
        while (*name && (**name != key)) name++;
        if (*name) {
            values[name-argnames] = value;
        } else {
            #if PY_MAJOR_VERSION < 3
            if (unlikely(!PyString_CheckExact(key)) && unlikely(!PyString_Check(key))) {
            #else
            if (unlikely(!PyUnicode_CheckExact(key)) && unlikely(!PyUnicode_Check(key))) {
            #endif
                goto invalid_keyword_type;
            } else {
                for (name = first_kw_arg; *name; name++) {
                    #if PY_MAJOR_VERSION >= 3
                    if (PyUnicode_GET_SIZE(**name) == PyUnicode_GET_SIZE(key) &&
                        PyUnicode_Compare(**name, key) == 0) break;
                    #else
                    if (PyString_GET_SIZE(**name) == PyString_GET_SIZE(key) &&
                        _PyString_Eq(**name, key)) break;
                    #endif
                }
                if (*name) {
                    values[name-argnames] = value;
                } else {
                    /* unexpected keyword found */
                    for (name=argnames; name != first_kw_arg; name++) {
                        if (**name == key) goto arg_passed_twice;
                        #if PY_MAJOR_VERSION >= 3
                        if (PyUnicode_GET_SIZE(**name) == PyUnicode_GET_SIZE(key) &&
                            PyUnicode_Compare(**name, key) == 0) goto arg_passed_twice;
                        #else
                        if (PyString_GET_SIZE(**name) == PyString_GET_SIZE(key) &&
                            _PyString_Eq(**name, key)) goto arg_passed_twice;
                        #endif
                    }
                    if (kwds2) {
                        if (unlikely(PyDict_SetItem(kwds2, key, value))) goto bad;
                    } else {
                        goto invalid_keyword;
                    }
                }
            }
        }
    }
    return 0;
arg_passed_twice:
    __Pyx_RaiseDoubleKeywordsError(function_name, **name);
    goto bad;
invalid_keyword_type:
    PyErr_Format(PyExc_TypeError,
        "%s() keywords must be strings", function_name);
    goto bad;
invalid_keyword:
    PyErr_Format(PyExc_TypeError,
    #if PY_MAJOR_VERSION < 3
        "%s() got an unexpected keyword argument '%s'",
        function_name, PyString_AsString(key));
    #else
        "%s() got an unexpected keyword argument '%U'",
        function_name, key);
    #endif
bad:
    return -1;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = __Pyx_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunctionObjArgs(__import__,
        name, global_dict, empty_dict, list, NULL);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                type = 0;
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) Py_TYPE(type);
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    __Pyx_ErrRestore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static INLINE void __Pyx_ErrRestore(PyObject *type, PyObject *value, PyObject *tb) {
    PyObject *tmp_type, *tmp_value, *tmp_tb;
    PyThreadState *tstate = PyThreadState_GET();

#if PY_MAJOR_VERSION >= 3
    /* Note: this is a temporary work-around to prevent crashes in Python 3.0 */
    if ((tstate->exc_type != NULL) & (tstate->exc_type != Py_None)) {
        tmp_type = tstate->exc_type;
        tmp_value = tstate->exc_value;
        tmp_tb = tstate->exc_traceback;
        PyErr_NormalizeException(&type, &value, &tb);
        PyErr_NormalizeException(&tmp_type, &tmp_value, &tmp_tb);
        tstate->exc_type = 0;
        tstate->exc_value = 0;
        tstate->exc_traceback = 0;
        PyException_SetContext(value, tmp_value);
        Py_DECREF(tmp_type);
        Py_XDECREF(tmp_tb);
    }
#endif

    tmp_type = tstate->curexc_type;
    tmp_value = tstate->curexc_value;
    tmp_tb = tstate->curexc_traceback;
    tstate->curexc_type = type;
    tstate->curexc_value = value;
    tstate->curexc_traceback = tb;
    Py_XDECREF(tmp_type);
    Py_XDECREF(tmp_value);
    Py_XDECREF(tmp_tb);
}

static INLINE void __Pyx_ErrFetch(PyObject **type, PyObject **value, PyObject **tb) {
    PyThreadState *tstate = PyThreadState_GET();
    *type = tstate->curexc_type;
    *value = tstate->curexc_value;
    *tb = tstate->curexc_traceback;

    tstate->curexc_type = 0;
    tstate->curexc_value = 0;
    tstate->curexc_traceback = 0;
}


static INLINE void __Pyx_RaiseNeedMoreValuesError(Py_ssize_t index) {
    PyErr_Format(PyExc_ValueError,
        #if PY_VERSION_HEX < 0x02050000
                 "need more than %d value%s to unpack", (int)index,
        #else
                 "need more than %zd value%s to unpack", index,
        #endif
                 (index == 1) ? "" : "s");
}

static INLINE void __Pyx_RaiseTooManyValuesError(void) {
    PyErr_SetString(PyExc_ValueError, "too many values to unpack");
}

static PyObject *__Pyx_UnpackItem(PyObject *iter, Py_ssize_t index) {
    PyObject *item;
    if (!(item = PyIter_Next(iter))) {
        if (!PyErr_Occurred()) {
            __Pyx_RaiseNeedMoreValuesError(index);
        }
    }
    return item;
}

static int __Pyx_EndUnpack(PyObject *iter) {
    PyObject *item;
    if ((item = PyIter_Next(iter))) {
        Py_DECREF(item);
        __Pyx_RaiseTooManyValuesError();
        return -1;
    }
    else if (!PyErr_Occurred())
        return 0;
    else
        return -1;
}

static INLINE int __Pyx_StrEq(const char *s1, const char *s2) {
     while (*s1 != '\0' && *s1 == *s2) { s1++; s2++; }
     return *s1 == *s2;
}

static INLINE unsigned char __Pyx_PyInt_AsUnsignedChar(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned char)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (unsigned char)-1;
            if (unlikely(val < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned char");
                return (unsigned char)-1;
            }
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return (unsigned char)val;
    }
    return (unsigned char)__Pyx_PyInt_AsUnsignedLong(x);
}

static INLINE unsigned short __Pyx_PyInt_AsUnsignedShort(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned short)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (unsigned short)-1;
            if (unlikely(val < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned short");
                return (unsigned short)-1;
            }
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return (unsigned short)val;
    }
    return (unsigned short)__Pyx_PyInt_AsUnsignedLong(x);
}

static INLINE unsigned int __Pyx_PyInt_AsUnsignedInt(PyObject* x) {
    if (sizeof(unsigned int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned int)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (unsigned int)-1;
            if (unlikely(val < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned int");
                return (unsigned int)-1;
            }
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to unsigned int");
            return (unsigned int)-1;
        }
        return (unsigned int)val;
    }
    return (unsigned int)__Pyx_PyInt_AsUnsignedLong(x);
}

static INLINE char __Pyx_PyInt_AsChar(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(char)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (char)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to char");
            return (char)-1;
        }
        return (char)val;
    }
    return (char)__Pyx_PyInt_AsLong(x);
}

static INLINE short __Pyx_PyInt_AsShort(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(short)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (short)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to short");
            return (short)-1;
        }
        return (short)val;
    }
    return (short)__Pyx_PyInt_AsLong(x);
}

static INLINE int __Pyx_PyInt_AsInt(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(int)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (int)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to int");
            return (int)-1;
        }
        return (int)val;
    }
    return (int)__Pyx_PyInt_AsLong(x);
}

static INLINE signed char __Pyx_PyInt_AsSignedChar(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed char)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (signed char)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to signed char");
            return (signed char)-1;
        }
        return (signed char)val;
    }
    return (signed char)__Pyx_PyInt_AsSignedLong(x);
}

static INLINE signed short __Pyx_PyInt_AsSignedShort(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed short)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (signed short)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to signed short");
            return (signed short)-1;
        }
        return (signed short)val;
    }
    return (signed short)__Pyx_PyInt_AsSignedLong(x);
}

static INLINE signed int __Pyx_PyInt_AsSignedInt(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed int)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (signed int)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to signed int");
            return (signed int)-1;
        }
        return (signed int)val;
    }
    return (signed int)__Pyx_PyInt_AsSignedLong(x);
}

static INLINE unsigned long __Pyx_PyInt_AsUnsignedLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned long");
            return (unsigned long)-1;
        }
        return (unsigned long)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        if (unlikely(Py_SIZE(x) < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned long");
            return (unsigned long)-1;
        }
        return PyLong_AsUnsignedLong(x);
    } else {
        unsigned long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (unsigned long)-1;
        val = __Pyx_PyInt_AsUnsignedLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __Pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned PY_LONG_LONG");
            return (unsigned PY_LONG_LONG)-1;
        }
        return (unsigned PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        if (unlikely(Py_SIZE(x) < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned PY_LONG_LONG");
            return (unsigned PY_LONG_LONG)-1;
        }
        return PyLong_AsUnsignedLongLong(x);
    } else {
        unsigned PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (unsigned PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE long __Pyx_PyInt_AsLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        return (long)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        return PyLong_AsLong(x);
    } else {
        long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (long)-1;
        val = __Pyx_PyInt_AsLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE PY_LONG_LONG __Pyx_PyInt_AsLongLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        return (PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        return PyLong_AsLongLong(x);
    } else {
        PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE signed long __Pyx_PyInt_AsSignedLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        return (signed long)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        return PyLong_AsLong(x);
    } else {
        signed long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (signed long)-1;
        val = __Pyx_PyInt_AsSignedLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE signed PY_LONG_LONG __Pyx_PyInt_AsSignedLongLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        return (signed PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        return PyLong_AsLongLong(x);
    } else {
        signed PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (signed PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsSignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    #if PY_MAJOR_VERSION < 3
    empty_string = PyString_FromStringAndSize("", 0);
    #else
    empty_string = PyBytes_FromStringAndSize("", 0);
    #endif
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_GET(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode && (!t->is_identifier)) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_identifier || (t->is_unicode && t->intern)) {
            *t->p = PyUnicode_InternFromString(t->s);
        } else if (t->is_unicode) {
            *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

/* Type Conversion Functions */

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if ((x == Py_False) | (x == Py_None)) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PyObject* __Pyx_PyNumber_Int(PyObject* x) {
  PyNumberMethods *m;
  const char *name = NULL;
  PyObject *res = NULL;
#if PY_VERSION_HEX < 0x03000000
  if (PyInt_Check(x) || PyLong_Check(x))
#else
  if (PyLong_Check(x))
#endif
    return Py_INCREF(x), x;
  m = Py_TYPE(x)->tp_as_number;
#if PY_VERSION_HEX < 0x03000000
  if (m && m->nb_int) {
    name = "int";
    res = PyNumber_Int(x);
  }
  else if (m && m->nb_long) {
    name = "long";
    res = PyNumber_Long(x);
  }
#else
  if (m && m->nb_int) {
    name = "int";
    res = PyNumber_Long(x);
  }
#endif
  if (res) {
#if PY_VERSION_HEX < 0x03000000
    if (!PyInt_Check(res) && !PyLong_Check(res)) {
#else
    if (!PyLong_Check(res)) {
#endif
      PyErr_Format(PyExc_TypeError,
                   "__%s__ returned non-%s (type %.200s)",
                   name, name, Py_TYPE(res)->tp_name);
      Py_DECREF(res);
      return NULL;
    }
  }
  else if (!PyErr_Occurred()) {
    PyErr_SetString(PyExc_TypeError,
                    "an integer is required");
  }
  return res;
}

static INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE PyObject * __Pyx_PyInt_FromSize_t(size_t ival) {
#if PY_VERSION_HEX < 0x02050000
   if (ival <= LONG_MAX)
       return PyInt_FromLong((long)ival);
   else {
       unsigned char *bytes = (unsigned char *) &ival;
       int one = 1; int little = (int)*(unsigned char*)&one;
       return _PyLong_FromByteArray(bytes, sizeof(size_t), little, 0);
   }
#else
   return PyInt_FromSize_t(ival);
#endif
}

static INLINE size_t __Pyx_PyInt_AsSize_t(PyObject* x) {
   unsigned PY_LONG_LONG val = __Pyx_PyInt_AsUnsignedLongLong(x);
   if (unlikely(val == (unsigned PY_LONG_LONG)-1 && PyErr_Occurred())) {
       return (size_t)-1;
   } else if (unlikely(val != (unsigned PY_LONG_LONG)(size_t)val)) {
       PyErr_SetString(PyExc_OverflowError,
                       "value too large to convert to size_t");
       return (size_t)-1;
   }
   return (size_t)val;
}


